
//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//
// Alternative: https://xbm.jazzychad.net
//------------------------------------------------------------------------------

// WiFi symbol 9 x 9 pixels  ------------------------------------
static unsigned char WiFi_symbol[] PROGMEM = {
    0x00, 0xfe, 0x38, 0xfe, 0xee, 0xfe, 0x83, 0xff, 0x38, 0xfe, 0x6c, 0xfe,
    0x00, 0xfe, 0x38, 0xfe, 0x10, 0xfe};

void drawWiFi()
{
    if (WIFI_ON)
        display.drawXbm(115, 15, 9, 9, WiFi_symbol);
}